### ISSUE TITLE
Explain usage of use_builders and namedtuple_optional

### ISSUE THREAD

**Issue by pilgrim2go** [andychase/pipeless#1]
Hi Andy,

pipeless is dead simple.  Can you help explain more about  usage of use_builders and namedtuple_optional?

Thanks,
Pilgrim

**Comment by andychase** [comment]
There's some examples in `examples.py`, namely:

```
Function Builders
>>> function, run, _ = pipeline(lambda item, e: None, use_builders=True)
>>> @function
... def bob_the_builder(): return lambda _: _+1
>>> list(run([1,2,3]))
[2, 3, 4]

Optional NamedTuples
>>> from pipeless import namedtuple_optional
>>> new_class = namedtuple_optional({'field': 'value'}, 'cool_class')
>>> my_instance = new_class()
>>> my_instance.field
'value'
```

Basically function builders runs the function and treats the result as the data processor. I use this like so in my projects:

```
function, run, _ = pipeline(lambda item, e: None, use_builders=True)
@function
def my_builder():
    import my_library
    option = 12
    def my_pipe_step(item):
        return my_library.operation(item, option)
```

The reason I have it set up this way for my projects is because I have a lot of imports and I like to keep those libraries and options scoped with their data processor function.

Don't use Optional NamedTuples, they should be depreciated/removed. More information if you are interested: What they are trying to solve is using NamedTuples when some fields should have default values. The replacement solution you should use is to make a prototype NameTuple value for your data with all the default values set and when you want to make new objects run `.replace()` with the fields you want changed. I hope this makes sense.

**Comment by andychase** [comment]
Let me know if you have any further questions!

**Comment by andychase** [comment]
These features were removed from the library in version 2.0 since good alternatives are available.
